### PR TITLE
Added support for double plural (Duals) for languages like Arabic

### PR DESCRIPTION
**Pull request by Ayman-Kortobaa**
It's a simple change to add support for languages with duals or double plural.
The list of languages included on the wikipedia page [here](https://en.wikipedia.org/wiki/Dual_(grammatical_number)).

Thanks for the great package!

### CODE REVIEW

**Comment by Ayman-Kortobaa** [comment]
For clarification I have only changed 2 lines in 2 files, the rest of changes are due to `dartfmt`.
More precisely I added these two lines:
in `lib/constants.dart`
```dart
  static const String pluralTwo = '2';
```

and in `lib/localization.dart`
```dart
      case 2:
        return Constants.pluralTwo;
```

**Comment by bratan** [comment]
Thanks for the pull request, however I will not merge this since the code formatting should not be changed. Additionally the examples and the documentation would need to be updated as well.

**Comment by Ayman-Kortobaa** [comment]
Thanks for the feedback.
Totally understandable, I will add another PR without changing code formatting and updating docs and examples.

**Comment by bratan** [comment]
Thanks @Ayman-Kortobaa

**Pull request closed without merging**
