### PR TITLE
Support null safety

### PR DESCRIPTION
**Pull request by FelixMoMo**

### CODE REVIEW

**Comment by yashmittalJTG** [comment]
Running "flutter pub get" in chqbook-mobile...                  
Because every version of flutter_driver from sdk depends on crypto 2.1.5 and universal_io >=2.0.0 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with universal_io >=2.0.0.

And because every version of flutter_translate from git depends on universal_io ^2.0.1, flutter_driver from sdk is incompatible with flutter_translate from git.


this error is coming while upgrading to flutter v2.0.5

**Comment by trustmefelix** [comment]
@yashmittalJTG I could not replicate your issue. Anyhow I have just upgraded version of universal_io and collection. And below is reference for my flutter doctor result:

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Users/felixmo/flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/felixmo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.85

**Comment by rafaelsetragni** [comment]
I also did a null-safety version. If you guys wanna to merge it with yours, be welcome.

[Pull request: Migration to Null-safety](https://github.com/bratan/flutter_translate/pull/70)

**Comment by rafaelsetragni** [comment]
I did a new one, more simple to merge, without so much improvement.

[Pull request: More simple null safety migration](https://github.com/bratan/flutter_translate/pull/71)

**Pull request closed without merging**
