### PR TITLE
Support Null safety

### PR DESCRIPTION
**Pull request by leynier**

### CODE REVIEW

**Comment by leynier** [comment]
Fix #62

**Comment by leynier** [comment]
PR also in dependency: https://github.com/bratan/flutter_device_locale/pull/13

**Comment by leynier** [comment]
In this PR in pubspec.yml the dependency use a fork of the original dependency because the original dependency not yet migrate to null safety, but, Im also made a PR for support null safety in the origina dependency.

**Comment by nohli** [comment]
@leynier
Tried your fork, it crashed:

error

Fixed it, see https://github.com/bratan/flutter_device_locale/pull/13

**Pull request closed without merging**
