### PR TITLE
Migration to Null-safety

### PR DESCRIPTION
**Pull request by rafaelsetragni**
Migration to null-safety
Dependencies upgraded
Example Android Folder upraged to support dart 2
Added pt-BR as translation example
Formated Lib folder to pub.dev patterns with dartfmt command

### CODE REVIEW

**Comment by bratan** [comment]
Why would you mix the migration to null safety with refactoring, adding new language as example and other things?

**Comment by rafaelsetragni** [comment]
> Why would you mix the migration to null safety with refactoring, adding new language as example and other things?

Because it was so simple to do, that i did it once.

**Comment by bratan** [comment]
> > Why would you mix the migration to null safety with refactoring, adding new language as example and other things?
> 
> Because it was so simple to do, that i did it once.

This is not a good reason to mix everything. I would have to test all your changes in order to merge and I`m not going to do that. Additionally I see no reason for adding an additional language to the example, unless it is to showcase a new feature, which is not the case here.

**Comment by rafaelsetragni** [comment]
No problem. But i guess you should test everything anyway. Just my 2 cents.
And i added portuguese just because it is my home language.

**Comment by bratan** [comment]
> No problem. But i guess you should test everything anyway. Just my 2 cents.
> And i added portuguese just because it is my home language.

Thanks for your effort. 

The problem is that my time is limited, and one thing is testing and merging one feature, and another is X features/changes.

Regarding the language, basically adding additional languages would bloat the example, unless this is to showcase a feature as I mentioned. The current languages were implemented with the purpose of showcasing different features (I didn't add my native language either).

**Comment by rafaelsetragni** [comment]
Migration to null-safety  - main goal

Dependencies upgraded - necessary to achieve null-safety

Example Android Folder upgraged to support dart 2 - necessary because the old method "registerWith" is deprecated a long time ago. The changes was done only on Android folder

Added pt-BR as translation example - Really not necessary

Formated Lib folder to pub.dev patterns with dartfmt command - Necessary to make your plugin gets a higher score and be better ranked into pub.dev search engine. 
(This could be easly achieved using Android Studio, selecting the files and clicking on "Reformat code with dartfmt")

**Comment by bratan** [comment]
From your list only the first two are necessary to achieve the main goal and the rest optional, in any case I`m not going to continue this discussion. Good luck.

**Pull request closed without merging**
